### PR TITLE
[DOC] add control loop documentation

### PR DESCRIPTION
**Pull request by lokiledev**
fix https://github.com/yconst/Tinymovr/issues/53

I added a `control` section in the doc with my schema of the position control loop.
The chapter is probably too verbose, I'll follow your review.

### CODE REVIEW

**Comment by yconst** [comment]
Awesome, thanks! If you don't mind, I'd like to perform a few additions, and a few changes to the structure of the documentation mainly. Then I will merge.

**Comment by lokiledev** [comment]
Yes feel free to edit as you like. I can reword the schema also if you want.

**Comment by yconst** [comment]
I updated the document. Please take a look, if you do not have any comments I can merge.

**Review by lokiledev — COMMENTED** [review]
Looks good to me, very detailed and clear :)

**Comment by yconst** [comment]
> Looks good to me, very detailed and clear :)

Cool! Thanks a lot for the contribution!

**Pull request merged**
